#!/usr/bin/env python3
"""Generate two clean, spec-conforming sample splat PLY files.

Stdlib-only (no numpy) so this runs anywhere: uses `struct` for the exact
binary layout and `random`/`math` for value generation. Deterministic (fixed
seed) so re-running produces byte-identical output.

Usage:
    python3 scripts/make_samples.py

Writes:
    samples/sample_small.ply  (~500 gaussians)
    samples/sample_large.ply  (~5000 gaussians)

See docs/splat-ply-spec.md for the field-by-field encoding this follows.
"""
import math
import os
import random
import struct

SH_C0 = 0.28209479177387814
HEADER_FIELDS = [
    "x", "y", "z",
    "nx", "ny", "nz",
    "f_dc_0", "f_dc_1", "f_dc_2",
    "opacity",
    "scale_0", "scale_1", "scale_2",
    "rot_0", "rot_1", "rot_2", "rot_3",
]

HERE = os.path.dirname(os.path.abspath(__file__))
SAMPLES_DIR = os.path.join(os.path.dirname(HERE), "samples")


def make_header(n_vertices):
    lines = [
        "ply",
        "format binary_little_endian 1.0",
        "comment synthetic sample generated by scripts/make_samples.py",
        f"element vertex {n_vertices}",
    ]
    lines += [f"property float {name}" for name in HEADER_FIELDS]
    lines.append("end_header")
    return ("\n".join(lines) + "\n").encode("ascii")


def rgb_to_f_dc(r, g, b):
    return tuple((c - 0.5) / SH_C0 for c in (r, g, b))


def alpha_to_opacity(a):
    return math.log(a / (1.0 - a))


def make_gaussian_record(rng, extent):
    # Position: a point somewhere inside a cube of the given half-extent,
    # loosely clustered toward the center to look like a plausible scanned
    # room/object rather than uniform noise.
    x = rng.gauss(0.0, extent * 0.35)
    y = rng.gauss(0.0, extent * 0.35)
    z = rng.gauss(0.0, extent * 0.20)

    # Normals: baseline exporter always writes zero (see spec).
    nx = ny = nz = 0.0

    # Color: plausible RGB in [0,1], encoded as SH DC.
    r = rng.uniform(0.05, 0.95)
    g = rng.uniform(0.05, 0.95)
    b = rng.uniform(0.05, 0.95)
    f_dc_0, f_dc_1, f_dc_2 = rgb_to_f_dc(r, g, b)

    # Opacity: baseline exporter uses one constant alpha for the whole file;
    # a tiny bit of per-point jitter is added here just so the sample isn't
    # perfectly degenerate for summary-stats exercises.
    a = min(0.999, max(0.001, rng.gauss(0.9, 0.02)))
    opacity = alpha_to_opacity(a)

    # Scale: derived from a plausible local point-spacing distribution
    # (log-normal is a reasonable stand-in for "mean distance to k nearest
    # neighbours" in a real point cloud).
    size = rng.lognormvariate(math.log(0.01), 0.5)  # centered ~1cm
    scale = math.log(size)

    # Rotation: identity quaternion (w, x, y, z) = (1, 0, 0, 0), matching
    # the isotropic baseline exporter.
    rot_0, rot_1, rot_2, rot_3 = 1.0, 0.0, 0.0, 0.0

    return (
        x, y, z,
        nx, ny, nz,
        f_dc_0, f_dc_1, f_dc_2,
        opacity,
        scale, scale, scale,
        rot_0, rot_1, rot_2, rot_3,
    )


def write_sample(path, n, seed, extent=2.0):
    rng = random.Random(seed)
    header = make_header(n)
    with open(path, "wb") as f:
        f.write(header)
        for _ in range(n):
            record = make_gaussian_record(rng, extent)
            assert len(record) == 17
            f.write(struct.pack("<17f", *record))
    return header


def verify(path, expected_n):
    with open(path, "rb") as f:
        data = f.read()
    header_end = data.index(b"end_header\n") + len(b"end_header\n")
    header_text = data[:header_end].decode("ascii")
    body = data[header_end:]
    assert "format binary_little_endian 1.0" in header_text, path
    assert f"element vertex {expected_n}" in header_text, path
    prop_lines = [
        line.split()[-1]
        for line in header_text.splitlines()
        if line.startswith("property float")
    ]
    assert prop_lines == HEADER_FIELDS, (path, prop_lines)
    expected_bytes = expected_n * 17 * 4
    assert len(body) == expected_bytes, (path, len(body), expected_bytes)
    print(
        f"OK  {path}: header {len(prop_lines)} fields, "
        f"N={expected_n}, body={len(body)} bytes "
        f"(== {expected_n} * 68 = {expected_bytes})"
    )


def main():
    os.makedirs(SAMPLES_DIR, exist_ok=True)

    small_path = os.path.join(SAMPLES_DIR, "sample_small.ply")
    large_path = os.path.join(SAMPLES_DIR, "sample_large.ply")

    write_sample(small_path, n=500, seed=20260728, extent=1.0)
    write_sample(large_path, n=5000, seed=20260729, extent=3.0)

    verify(small_path, 500)
    verify(large_path, 5000)


if __name__ == "__main__":
    main()
